package logicits.javaccList;

/* Generated By:JavaCC: Do not edit this line. LogicoLexicoVisitor.java Version 6.0_1 */
public interface LogicoLexicoVisitor {

    public Object visit(SimpleNode node, Object data);

    public Object visit(ASTprogram node, Object data);
}
/* JavaCC - OriginalChecksum=49e37b34dcb24ac38f338e1342bbc425 (do not edit this line) */
