package logicits.javacclist;

/* Generated By:JavaCC: Do not edit this line. LogicoLexicoDefaultVisitor.java Version ??.??_?? */
public class LogicoLexicoDefaultVisitor implements LogicoLexicoVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprogram node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=226a3a443ed88f8df97c36463dda0739 (do not edit this line) */
