package logicits.javaccList;

/* Generated By:JJTree&JavaCC: Do not edit this line. LogicoLexicoConstants.java */
/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface LogicoLexicoConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int ABREPARENT = 1;
    /**
     * RegularExpression Id.
     */
    int FECHAPARENT = 2;
    /**
     * RegularExpression Id.
     */
    int LOGO = 3;
    /**
     * RegularExpression Id.
     */
    int E = 4;
    /**
     * RegularExpression Id.
     */
    int OU = 5;
    /**
     * RegularExpression Id.
     */
    int NEGACAO = 6;
    /**
     * RegularExpression Id.
     */
    int VARIAVEL = 7;
    /**
     * RegularExpression Id.
     */
    int BIIMPLICA = 8;
    /**
     * RegularExpression Id.
     */
    int MAIORQUE = 9;
    /**
     * RegularExpression Id.
     */
    int MENORQUE = 10;
    /**
     * RegularExpression Id.
     */
    int IMPLICA = 11;
    /**
     * RegularExpression Id.
     */
    int EHIMPLICADO = 12;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
        "<EOF>",
        "\"(\"",
        "\")\"",
        "\"|-\"",
        "\"&\"",
        "\"|\"",
        "\"~\"",
        "<VARIAVEL>",
        "\"<->\"",
        "\">\"",
        "\"<\"",
        "\"->\"",
        "\"<-\"",
        "\" \"",
        "\"\\r\\n\"",
        "\"\\n\"",
        "\"\\t\"",};

}
