/* Generated By:JavaCC: Do not edit this line. LogicoLexicoDefaultVisitor.java Version 6.0_1 */
public class LogicoLexicoDefaultVisitor implements LogicoLexicoVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprogram node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=26155b33007de090fce2b0054facc913 (do not edit this line) */
