/* Generated By:JavaCC: Do not edit this line. LogicoLexicoTreeConstants.java Version 6.0_1 */
public interface LogicoLexicoTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "program",
    "void",
  };
}
/* JavaCC - OriginalChecksum=91118fade92929c5165bdb2a2894a403 (do not edit this line) */
