package logicits.javacclist;

/* Generated By:JavaCC: Do not edit this line. LogicoLexicoTreeConstants.java Version ??.??_?? */
public interface LogicoLexicoTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "program",
    "void",
  };
}
/* JavaCC - OriginalChecksum=d94ef5a1a09cee35d664a3f03015e2df (do not edit this line) */
