package logicits.javacclist;

/* Generated By:JavaCC: Do not edit this line. LogicoLexicoVisitor.java Version ??.??_?? */
public interface LogicoLexicoVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
}
/* JavaCC - OriginalChecksum=b42971531732708e6f606c449643e190 (do not edit this line) */
