package logicits.javaccList;

/* Generated By:JJTree&JavaCC: Do not edit this line. LogicoLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LogicoLexicoConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int ABREPARENT = 1;
    /**
     * RegularExpression Id.
     */
    int FECHAPARENT = 2;
    /**
     * RegularExpression Id.
     */
    int E = 3;
    /**
     * RegularExpression Id.
     */
    int OU = 4;
    /**
     * RegularExpression Id.
     */
    int NEGACAO = 5;
    /**
     * RegularExpression Id.
     */
    int VARIAVEL = 6;
    /**
     * RegularExpression Id.
     */
    int BIIMPLICA = 7;
    /**
     * RegularExpression Id.
     */
    int IMPLICA = 8;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
        "<EOF>",
        "\"(\"",
        "\")\"",
        "\"&\"",
        "\"|\"",
        "\"~\"",
        "<VARIAVEL>",
        "\"<->\"",
        "\"->\"",
        "\" \"",
        "\"\\r\\n\"",
        "\"\\n\"",
        "\"\\t\"",};

}
